# After installing latest "docker compose" it insists this is obsolete and being ignored.  So I'll comment it out for now.
# version: '3.8'

services:
  abxrlib-for-webxr:
    container_name: abxrlib-for-webxr
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["--publish"]
    #volumes:
    #  - ./build:/opt/arborxr/build
    #  - ./dist:/opt/arborxr/dist
    #  - ./abxrlib-for-webxr:/opt/arborxr/abxrlib-for-webxr
