# After installing latest "docker compose" it insists this is obsolete and being ignored.  So I'll comment it out for now.
# version: '3.8'

services:
  abxrlib-for-webxr:
    container_name: abxrlib-for-webxr
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NEXT_VERSION=${NEXT_VERSION}
    command: ["--publish"]
    volumes:
      # Mount temp directory for version exchange (optional, fallback method)
      - /tmp:/tmp
      - ./build:/opt/arborxr/build
      - ./dist:/opt/arborxr/dist
      - ./testers:/opt/arborxr/testers    
    #  - ./abxrlib-for-webxr:/opt/arborxr/abxrlib-for-webxr
